lobbySpawn:
  world: world
  x: 176.5
  y: 77.0
  z: 284.5
  yaw: 0.0
  pitch: 0.0

maps:
  map1:
    name: Standard
    creator: Its_Enzo
    world: world
    spawn:
      x: 48.0
      y: 87.0
      z: -59.0
      yaw: 0.0
      pitch: 0.0
    catcherSpawn:
      x: 33.5
      y: 90.0
      z: -93.5
      yaw: 0.0
      pitch: 0.0
    validArrowArea:
      start:
        x: 23
        y: 86
        z: -110
      end:
        x: 43
        y: 91
        z: -73
    bases:
      base1:
        gateMaterial: FENCE
        spawn:
          x: 48.0
          y: 87.0
          z: -68
          yaw: 0.0
          pitch: 0.0
        area:
          start:
            x: 45
            y: 89
            z: -71
          end:
            x: 50
            y: 86
            z: -66
        entranceArea:
          start:
            x: 44
            y: 87
            z: -66
          end:
            x: 44
            y: 87
            z: -71
        exitArea:
          start:
            x: 45
            y: 87
            z: -72
          end:
            x: 50
            y: 87
            z: -72
      base2:
        gateMaterial: FENCE
        spawn:
          x: 48.0
          y: 87.0
          z: -114
          yaw: 0.0
          pitch: 0.0
        area:
          start:
            x: 45
            y: 89
            z: -112
          end:
            x: 50
            y: 86
            z: -117
        entranceArea:
          start:
            x: 50
            y: 87
            z: -111
          end:
            x: 45
            y: 87
            z: -111
        exitArea:
          start:
            x: 44
            y: 87
            z: -112
          end:
            x: 44
            y: 87
            z: -117
      base3:
        gateMaterial: FENCE
        spawn:
          x: 19.0
          y: 87.0
          z: -113
          yaw: 0.0
          pitch: 0.0
        area:
          start:
            x: 21
            y: 89
            z: -112
          end:
            x: 16
            y: 86
            z: -117
        entranceArea:
          start:
            x: 22
            y: 87
            z: -117
          end:
            x: 22
            y: 87
            z: -112
        exitArea:
          start:
            x: 21
            y: 87
            z: -111
          end:
            x: 16
            y: 87
            z: -111
      base4:
        gateMaterial: FENCE
        spawn:
          x: 19.0
          y: 87.0
          z: -68
          yaw: 0.0
          pitch: 0.0
        area:
          start:
            x: 21
            y: 89
            z: -71
          end:
            x: 16
            y: 86
            z: -66
        entranceArea:
          start:
            x: 16
            y: 87
            z: -72
          end:
            x: 21
            y: 87
            z: -72
        exitArea:
          start:
            x: 22
            y: 87
            z: -71
          end:
            x: 22
            y: 87
            z: -66
    hoppers:
      hopper1:
        x: 33
        y: 88
        z: -92
      hopper2:
        x: 33
        y: 88
        z: -91