lobbySpawn:
  world: world
  x: -857.5
  y: 242.0
  z: -119.5
  yaw: 90.0
  pitch: 0.0

maps:
  map1:
    name: Standard
    creator: GreenGlowPixel
    world: world
    catcherSpawn:
      x: -598.5
      y: 248.0
      z: -67.5
      yaw: -90.0
      pitch: 0.0
    runnerSpawn:
      x: -516.5
      y: 248.0
      z: -31.5
      yaw: -90.0
      pitch: 0.0
    armorStands:
      armorStand1:
        x: -558.5
        y: 248.0
        z: -49.5
      armorStand2:
        x: -558.5
        y: 248.0
        z: -30.5
      armorStand3:
        x: -554.5
        y: 248.0
        z: -28.5
      armorStand4:
        x: -563.5
        y: 248.0
        z: -66.5
      armorStand5:
        x: -550.5
        y: 248.0
        z: -43.5
      armorStand6:
        x: -552.5
        y: 248.0
        z: -61.5
      armorStand7:
        x: -542.5
        y: 248.0
        z: -54.5
      armorStand8:
        x: -540.5
        y: 248.0
        z: -61.5
      armorStand9:
        x: -540.5
        y: 248.0
        z: -43.5
      armorStand10:
        x: -528.5
        y: 248.0
        z: -31.5
      armorStand11:
        x: -522.5
        y: 248.0
        z: -55.5
      armorStand12:
        x: -527.5
        y: 248.0
        z: -67.5
    rescueCapsule:
      entranceMaterial: GLASS
      entranceArea:
        start:
          x: -522
          y: 250
          z: -27
        end:
          x: -524
          y: 248
          z: -27
      exitMaterial: QUARTZ_BLOCK
      exitArea:
        start:
          x: -524
          y: 247
          z: -26
        end:
          x: -522
          y: 247
          z: -23
      rescueButtonLocation:
        x: -523
        y: 248
        z: -23
    void:
      area:
        start:
          x: -601
          y: 245
          z: -60
        end:
          x: -567
          y: 255
          z: -26
      toLocation:
        x: -607
        y: 254
        z: -22
    teleportationPoints:
      point1:
        x: -555.5
        y: 248.0
        z: -56.5
        yaw: 270.0
        pitch: 0.0
      point2:
        x: -546.5
        y: 248.0
        z: -34.5
        yaw: 90.0
        pitch: 0.0
      point3:
        x: -533.5
        y: 248.0
        z: -68.5
        yaw: 0.0
        pitch: 0.0
      point4:
        x: -529.5
        y: 248.0
        z: -31.5
        yaw: 270.0
        pitch: 0.0
      point5:
        x: -514.5
        y: 248.5
        z: -48.5
        yaw: 90.0
        pitch: 0.0
