lobbySpawn:
  world: world
  x: -857.5
  y: 242.0
  z: -119.5
  yaw: 90.0
  pitch: 0.0

maps:
  map1:
    name: Standard
    creator: GreenGlowPixel
    world: world
    catcherSpawn:
      x: -598.5
      y: 248.0
      z: -67.5
      yaw: -90.0
      pitch: 0.0
    runnerSpawns:
      spawn1:
        x: -516.5
        y: 248.0
        z: -31.5
        yaw: -90.0
        pitch: 0.0
    armorStands:
      armorStand1:
        x: -559.5
        y: 248.0
        z: -50.5
      armorStand2:
        x: -559.5
        y: 248.0
        z: -31.5
      armorStand3:
        x: -555.5
        y: 248.0
        z: -29.5
      armorStand4:
        x: -564.5
        y: 248.0
        z: -67.5
      armorStand5:
        x: -551.5
        y: 248.0
        z: -44.5
      armorStand6:
        x: -553.5
        y: 248.0
        z: -62.5
      armorStand7:
        x: -543.5
        y: 248.0
        z: -55.5
      armorStand8:
        x: -541.5
        y: 248.0
        z: -62.5
      armorStand9:
        x: -541.5
        y: 248.0
        z: -44.5
      armorStand10:
        x: -529.5
        y: 248.0
        z: -32.5
      armorStand11:
        x: -523.5
        y: 248.0
        z: -56.5
      armorStand12:
        x: -528.5
        y: 248.0
        z: -68.5
    rescueCapsule:
      entranceMaterial: GLASS
      entranceArea:
        start:
          x: -522
          y: 250
          z: -27
        end:
          x: -524
          y: 248
          z: -27
      exitMaterial: QUARTZ_BLOCK
      exitArea:
        start:
          x: -524
          y: 247
          z: -26
        end:
          x: -522
          y: 247
          z: -23
      rescueButtonLocation:
        x: -523
        y: 248
        z: -23
    void:
      area:
        start:
          x: -601
          y: 245
          z: -60
        end:
          x: -567
          y: 255
          z: -26
      toLocation:
        x: -607
        y: 254
        z: -22
